Add syntax highlight for code blocks
umami-software/website pull request #111
Opened 2023-02-24 14:55 UTC by nkilm

## Additions
- Used [rehype-pretty-code](https://rehype-pretty-code.netlify.app/) for [build-time](https://rehype-pretty-code.netlify.app/#:~:text=There%27s%20no%20runtime%20or%20bundle%20size%20cost) syntax highlighting. 
- Theme used - `one-dark-pro`, theme can be changed in [next.config.js](https://github.com/umami-software/website/blob/master/next.config.js).

## Related Issues 
#103 - Syntax Highlighting in docs

## Example
checkout the code snippet here  - `/docs/running-on-vercel`

```js
// mentioning programming language is important to highlight appropriate keywords
<script
  async
  defer
  src="/stats/script.js"
  data-website-id="94db1cb1-74f4-4a40-ad6c-962362670409"
></script>
```

![image](https://user-images.githubusercontent.com/79012023/221207967-0c6eadc9-ed4a-4147-90ea-4cfde35f6030.png)

## References
- [https://rehype-pretty-code.netlify.app/](https://rehype-pretty-code.netlify.app/)
- Supported themes - [shiki-themes](https://github.com/shikijs/shiki/blob/main/docs/themes.md)

2023-08-22 22:54 UTC, uncenter requested changes
Looks solid though.

2023-08-22 22:54 UTC, uncenter commented on content/running-on-vercel.mdx
This file shouldn't have any changes.

2023-08-22 22:54 UTC, uncenter commented on next.config.js
> +  theme: 'one-dark-pro',
Theme looks good! You could probably remove the comment though.

2023-08-23 06:30 UTC, nkilm commented on next.config.js
> +  theme: 'one-dark-pro',
Alright, I'll remove the comments.

2023-08-23 06:31 UTC, nkilm commented on content/running-on-vercel.mdx
Alright, I'll update the code in this branch by merging with main. We do have to mention the language for code snippets to get proper syntax highlight.

2023-08-23 06:32 UTC, uncenter commented on content/running-on-vercel.mdx
Yeah I made a PR a little while back to add languages for all of the code blocks so this isn't necessary. Thanks for getting on this so quick!

2023-08-23 06:35 UTC, nkilm commented on content/running-on-vercel.mdx
That's great! I'll push the requested changes asap.

2023-08-23 16:10 UTC, uncenter commented
Nice work! One last thing. I was taking a look at the code blocks on the website and they look a little dull/grayish with the current theme. I messed around with a bunch of themes and `github-light` really looks nice. 

<img width="942" alt="image" src="https://github.com/umami-software/website/assets/47499684/318e5810-ee6a-4269-a19f-6e7be0d24cde">
<img width="937" alt="image" src="https://github.com/umami-software/website/assets/47499684/b9415881-e423-42aa-ad13-ef760600c1bb">
<img width="938" alt="image" src="https://github.com/umami-software/website/assets/47499684/67d19729-9f99-45e7-9a62-ead9db7c255a">
<img width="944" alt="image" src="https://github.com/umami-software/website/assets/47499684/cad781e8-cfe8-4b53-a0c9-e3a85fb27fd3">

Thoughts? It seems much sharper and stands out more.

2023-08-23 17:24 UTC, nkilm commented
Yeah I was about mention that!😅

I'll change the theme to `github-light`.

2023-08-23 17:44 UTC, nkilm commented
@uncenter Done✅

2023-08-23 18:36 UTC, uncenter commented on package.json
> +    "react-tooltip": "^4.2.21",
Why is `react-tooltip` added?

2023-08-23 18:37 UTC, uncenter commented on package.json
> +    "react-tooltip": "^4.2.21",
I'm guessing it somehow got added in the merge commit but I'm not seeing it on the `master` branch...

2023-08-25 06:38 UTC, nkilm commented on package.json
> +    "react-tooltip": "^4.2.21",
Yeah I didn't notice this part, I was having some merge conflicts this got added there. I'll remove it.

2023-08-25 11:13 UTC, nkilm commented
@uncenter I've removed that package.

2023-08-25 15:08 UTC, uncenter commented
> @uncenter I've removed that package.

Did you run the uninstall command or just remove it from the package.json? Looks like you had a build failure as soon as you did that.

2023-08-26 17:41 UTC, nkilm commented
> > @uncenter I've removed that package.
> 
> Did you run the uninstall command or just remove it from the package.json? Looks like you had a build failure as soon as you did that.

I didn't remove it using `yarn uninstall`. I did it manually. I'll fix it now, also are there any other changes which are to be made?

2023-08-26 17:42 UTC, uncenter commented
I think that's it. If the build succeeds + no unnecessary files are changed, it should be good to go.

2023-08-27 09:39 UTC, nkilm commented
Alright

2023-08-27 17:47 UTC, nkilm commented
@uncenter I've fixed the issue now, build is successful.

2023-08-27 18:02 UTC, uncenter approved these changes

2023-09-01 09:03 UTC, mikecao commented
We've made major changes to the website, so instead of dealing with merge conflicts, I implemented your solution. It's live on the website now. Closing this PR.

2023-09-01 09:03 UTC, closed without merging

2023-09-01 15:26 UTC, uncenter commented
Great! New design + syntax highlighting looking good.